### ISSUE TITLE
Build is not reproductible (JS tools issue)

### ISSUE THREAD

**Issue by gibello** [roboconf/roboconf-web-administration#15]
Depending on the system and tools versions (eg. bower, npm ?), the build is not reproductible - and may produce different files, some inducing runtime errors.
That makes the bug itself difficult to reproduce (sic).

**Comment by vincent-zurczak** [comment]
No problem so far with my tests for version 0.2.

**Comment by vincent-zurczak** [comment]
The problem occurs again with Karaf.
I Think this is related to the browser's cache (the Karaf URL is not the same than with NodeJS).

We should stop using Bootstrap's modal dialogs and only rely on the safety page.
