### ISSUE TITLE
Application/Template icons are never used

### ISSUE THREAD

**Issue by bourretp** [roboconf/roboconf-web-administration#53]
In the application/template listing, the displayed icons are coloured variants of the Roboconf logo.
However, when an template archive contains (e.g.) a `application.png` image in the root directory, it is not taken in account by the web-admin. Same thing if the image is copied in the app/template working directory.

Worse: the platform `IconServlet` which is supposed to find the app/template icon is never called, which means the web-admin is missing something.

**Comment by vincent-zurczak** [comment]
That's weird, because it used to work.
I have made demos with custom icons. However, it may mean tests are not good enough. I will investigate it. :sweat_smile:

**Comment by bourretp** [comment]
Naahh, I'm over-guilty on this one... The ManagementResource.setImage() method (platform) copy the image at the wrong location: at app/template root instead of `descriptor`...
Closing! ... and sorry ;)
