### ISSUE TITLE
Add icon upload for applications

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-web-administration#58]
Everything is in the title.

**Comment by diarraa** [comment]
I see two manners to handle this issue.  The first one is to make the following javascript functions: ` `` **findAppIcon** that returns the app icon stored beforehand in **src/img** folder and **findAppAvatar** that customizes the icon (for example the background color). Then I add in  **_app-directive.html** file this code 
<p class="app-avatar">
		<img ng-src="{{ findAppIcon( app )}}" alt="application's icon" ng-class="findAppAvatar( app )"/>
</p>

The last one is to make a directive in javascript that contains a function **uploadIcon**  and use it (the same technique used to upload the application ZIP file)

**Comment by vincent-zurczak** [comment]
You do not need to find the icon (findIcon).
The icon location is already contained in the JSon (the one that describes an application) if it exists. Look for `APP_ICON` in [our JSon serializer](https://github.com/roboconf/roboconf-platform/blob/master/core/roboconf-dm-rest-commons/src/main/java/net/roboconf/dm/rest/commons/json/JSonBindingUtils.java). When there is no icon, a random avatar is picked up by the web administration.

What you need to do is to update the **_app-directive.html** file and plug a library to:

* Select an image on the disk when we click on a specific link.
* Crop this image.
* Invoke the "Upload" [REST API provided by the DM](https://github.com/roboconf/roboconf-platform/blob/master/core/roboconf-dm-rest-services/src/main/java/net/roboconf/dm/rest/services/internal/resources/IManagementResource.java).

[CropperJS](https://github.com/fengyuanchen/cropperjs) seems really cool. MIT license, Bower integration... They have a [demo site](https://fengyuanchen.github.io/photo-editor/) too. Take inspiration from it.

You should have modifications to do in the **_app-directive.html** file and in its controller. Plus one in **utils.service.rClient.js** to invoke the Roboconf's REST API. And you would have to add CropperJS (or any other library you might use) in the **dependencies** section of the **bower.json** file.
