### ISSUE TITLE
Add icons in the files packaging

### ISSUE THREAD

**Issue by donsez** [roboconf/roboconf-web-administration#6]
Add icons in the files packaging in order to display them in GUIs (web, eclipse, ...) and automatic documentation generation.

the icons could be located side by side with scripts
for instance:
...
roboconf-examples/apache-tomcat-bash/graph/Apache/scripts
roboconf-examples/apache-tomcat-bash/graph/Apache/icons

the icons could have several sizes
roboconf-examples/apache-tomcat-bash/graph/Apache/icons/16x16
roboconf-examples/apache-tomcat-bash/graph/Apache/icons/32x32
roboconf-examples/apache-tomcat-bash/graph/Apache/icons/64x64
...

and each icon could represent a state in the lifecycle
roboconf-examples/apache-tomcat-bash/graph/Apache/icons/32x32/unknown.png
roboconf-examples/apache-tomcat-bash/graph/Apache/icons/32x32/starting
roboconf-examples/apache-tomcat-bash/graph/Apache/icons/32x32/started
...

**Comment by vincent-zurczak** [comment]
Icons can now be displayed by the console.
